# Network-specific config options
network:
    # Hostex API URL
    hostex_api_url: https://api.hostex.io/v3
    # Admin user to receive startup notifications
    admin_user: "@yourusername:yourhomeserver.com"

# Config options that affect the central bridge module.
bridge:
    # The prefix for commands. Only required in non-management rooms.
    command_prefix: '!hostex'
    # Should the bridge create a space for each login containing the rooms that account is in?
    personal_filtering_spaces: true
    # Whether the bridge should set names and avatars explicitly for DM portals.
    private_chat_portal_meta: true
    
    # Permissions for using the bridge.
    # Permitted values:
    #    relay - Talk through the relaybot (if enabled), no access otherwise
    # commands - Access to use commands in the bridge, but not login.
    #     user - Access to use the bridge with puppeting.
    #    admin - Full access, user level with some additional administration tools.
    permissions:
        "*": relay
        "yourhomeserver.com": user
        "@yourusername:yourhomeserver.com": admin

# Config for the bridge's database.
database:
    # The database type. "sqlite3-fk-wal" and "postgres" are supported.
    type: sqlite3-fk-wal
    # The database URI.
    uri: file:mautrix-hostex.db?_txlock=immediate
    max_open_conns: 5
    max_idle_conns: 1

# Homeserver details.
homeserver:
    # The address that this appservice can use to connect to the homeserver.
    address: https://matrix.yourhomeserver.com
    # The domain of the homeserver (also known as server_name, used for MXIDs, etc)
    domain: yourhomeserver.com
    
    # Should the bridge use a websocket for connecting to the homeserver?
    websocket: false

# Application service host/registration related details.
appservice:
    # The address that the homeserver can use to connect to this appservice.
    address: http://localhost:29337
    # The hostname and port where this appservice should listen.
    hostname: 127.0.0.1
    port: 29337
    
    # The unique ID of this appservice.
    id: hostex-bridge
    # Appservice bot details.
    bot:
        # Username of the appservice bot.
        username: hostexbot
        # Display name and avatar for bot.
        displayname: Hostex bridge bot
        avatar: mxc://yourhomeserver.com/hostex-icon
    
    # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
    as_token: "your_as_token_here"
    hs_token: "your_hs_token_here"
    
    # Localpart template of MXIDs for remote users.
    # {{.}} is replaced with the internal ID of the user.
    username_template: hostex_{{.}}

# Settings for enabling double puppeting
double_puppet:
    # Servers to always allow double puppeting from.
    servers:
        yourhomeserver.com: https://matrix.yourhomeserver.com
    # Whether to allow client API URL discovery for other servers.
    allow_discovery: true

# Logging config.
logging:
    min_level: info
    writers:
        - type: stdout
          format: pretty-colored
        - type: file
          format: json
          filename: ./logs/bridge.log
          max_size: 100
          max_backups: 10